//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEARCHPORTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobapplicationtab
    {
        public int Application_ID { get; set; }
        public int User_Id { get; set; }
        public int Job_ID { get; set; }
        public System.DateTime Application_Date { get; set; }
        public string Application_Resume { get; set; }
        public string Application_Status { get; set; }
    }
}
