//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEARCHPORTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTab
    {
        public int Job_ID { get; set; }
        public int Company_ID { get; set; }
        public string Job_Title { get; set; }
        public string Job_Description { get; set; }
        public string Job_Skills { get; set; }
        public string Job_Experience { get; set; }
        public string Job_Type { get; set; }
        public string Job_WorkMode { get; set; }
        public string Job_Location { get; set; }
        public string Job_SalaryRange { get; set; }
        public System.DateTime Job_EndDate { get; set; }
        public string Job_Status { get; set; }
    }
}
