//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEARCHPORTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistrationTable
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Age { get; set; }
        public string User_Addres { get; set; }
        public string User_Phone { get; set; }
        public string User_Email { get; set; }
        public string User_Skills { get; set; }
        public string User_Experience { get; set; }
        public string User_Location { get; set; }
        public string User_Photo { get; set; }
        public string User_Qualification { get; set; }
        public string User_JobPreferences { get; set; }
    }
}
